# Generated by Django 4.2.7 on 2024-03-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hojavida',
            table='hojavida',
        ),
    ]
