# Generated by Django 5.0.2 on 2024-03-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regis_candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña_hashed', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
