# Generated by Django 4.2.7 on 2024-03-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='nombre_cargo',
            new_name='educacion',
        ),
        migrations.AddField(
            model_name='oferta',
            name='profecion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='experiencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='sueldo',
            field=models.FloatField(),
        ),
    ]
