# Generated by Django 4.2.7 on 2024-03-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ofertas',
        ),
    ]
