# Generated by Django 5.0.3 on 2024-03-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ofertas',
        ),
    ]
