# Generated by Django 5.0.3 on 2024-03-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('profecion', models.CharField(max_length=255)),
                ('experiencia', models.CharField(max_length=255)),
                ('educacion', models.CharField(max_length=255)),
                ('sueldo', models.FloatField()),
                ('tipo_contrato', models.CharField(max_length=255)),
                ('modalidad_trabajo', models.CharField(max_length=255)),
                ('localizacion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('n_vacantes', models.IntegerField()),
                ('postulaciones', models.IntegerField()),
            ],
        ),
    ]
